[workspace]
authors = ["marcbishara <6134115+marcbishara@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "project_RACE"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.14"
pip = "*"

[pypi-dependencies]
crazyflow = { path = "./crazyflow", editable = true }
imageio-ffmpeg = "*"

[feature.gpu.pypi-dependencies]
crazyflow = { path = "./crazyflow", editable = true, extras = ["gpu"] }

[environments]
default = { solve-group = "default" }
gpu = { features = ["gpu"], solve-group = "default" }
